### ISSUE TITLE
Lua Source Code Format

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#16]
_Whilst this is a fairly well known format it is still important that these details are standardised._

Extensions: `.lua` (and any other extensions you know of)
MIME: `text/lua`

**Comment by demhydraz** [comment]
I'll let my terminal session speak for itself:
```
matheus sleipnir Silica ⚡ mimetype font-converter.lua 
font-converter.lua: text/x-lua
```

**Comment by oeed** [comment]
I'd be interested in seeing what other OSes show. I'm getting both `text/plain` and ...`text/x-c++` so they're both clearly wrong...

What's the x- meant to mean?

**Comment by demhydraz** [comment]
Unregistered, iirc.

**Comment by demhydraz** [comment]
Yea, [RFC 1341 of the W3C](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) determines that
> If another primary type is to be used for any reason, it must be given a name starting with "X-" to indicate its non-standard status and to avoid a potential conflict with a future official name.

**Comment by oeed** [comment]
Well I reckon we just stick with text/lua.
