### ISSUE TITLE
Folder/Directory Standard

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#17]
_Whilst this isn't technically a file type it is still important that the MIME is standardised._

MIME: `folder`

The reasoning for giving folders a MIME is that some metadata systems allow folders to act like files and as such need a MIME.

**Comment by demhydraz** [comment]
MIME should be `inode/directory`.

**Comment by viluon** [comment]
MIME should be `directory`. CraftOS doesn't use/know `inode`s.

**Comment by demhydraz** [comment]
`application/directory`.

**Comment by oeed** [comment]
CraftOS doesn't know/use anything.

I'd have to agree with `application/directory` simply because it's more consistent with having a slash in it.

**Comment by viluon** [comment]
I agree with that @oeed

**Comment by demhydraz** [comment]
:+1:
