### ISSUE TITLE
Standard Versioning

### ISSUE THREAD

**Issue by viluon** [oeed/CraftOS-Standards#2]
Every standard definition should state its current version, and links (names, really) to standards that it should replace or is dependant upon. All earlier versions should contain a link to the latest version at the very top of the standard Markdown file. This would mean that old versions are kept in place (forever) and their definitions are never lost in the stream of standard updates but versioning is still possible.

Much like is the current practice with RFCs:

> Once assigned a number and published, an RFC is never rescinded or modified; if the document requires amendments, the authors publish a revised document. Therefore, some RFCs supersede others; the superseded RFCs are said to be deprecated, obsolete, or obsoleted by the superseding RFC.

**Comment by superaxander** [comment]
An advantage of this is that when a program complies with rfc 12345 it will stay that way as RFCs can't be updated. This way it is still clear what the program supports even if it hasn't been updated in quite a while.

**Comment by oeed** [comment]
If that's how RFCs are meant to be versioned then we'll stick with that.

**Comment by viluon** [comment]
Great! I'll add it to the guide I am writing in the `tutorial` branch :wink:
