### ISSUE TITLE
Expressing Keyboard Shortcuts

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#20]
It might be good to adopt a universal standard way of expressing keyboard shortcuts.

For example, how do you express control/command + C? OS X has a good way... if you actually know what the symbols mean.

If all programs use the same format there might be one less headache.

**Comment by demhydraz** [comment]
C-key for control-key, KEY for shift-key, S-key for super-key, M-key for
alt-key.

**Comment by demhydraz** [comment]
I must also point out that some applications use ^<key in uppercase>
meaning C-key. (i.e. ^C is C-c is Control+C)

**Comment by viluon** [comment]
Why not just write the whole key shortcut? Such as `Control + C`, `Control + Alt + Delete` or `Alt + F4`. Try the last one if you disagree with me. If it doesn't work, use `Control + Shift + W` or simply `Ctrl + W`.

**Comment by oeed** [comment]
@viluon because they're 23 characters long and take up half your screen.

**Comment by SquidDev** [comment]
I'd agree with @viluon That <kbd>Ctrl+W</kbd> is the best way of doing it: everyone is used to it, whilst many people will be confused about <kbd>^C</kbd> or <kbd>M-w</kbd>.

**Comment by demhydraz** [comment]
Many people should read the freaking spec, then.
Also, it's M-w.

**Comment by viluon** [comment]
And as you can see, @SquidDev used the right way to display them, which is using the HTML `<kbd>` tag!

**Comment by SquidDev** [comment]
I just don't feel that the average user needs to read a spec, you go for what people are used to/expect. Not everyone knows what the "meta" key is, but everyone knows where to find Alt.

**Comment by oeed** [comment]
You can't use ridiculously large strings though that'll use up most of the screen. I put the shortcuts in menus like OS X does and if you did that the menus would look ridiculous.

**Comment by viluon** [comment]
Agreed @oeed, but we are talking docs, not GUI here. I don't think that abbreviations are necessary, best-case scenario you don't even use contracted forms (i.e. _don't_ instead of _do not_) in the Markdown document, so why should you do that with keyboard shortcuts? They aren't that long anyway.

**Comment by demhydraz** [comment]
<kbd>C-x M-c M-butterfly</kbd> is considerably shorter than <kbd>Ctrl+X Alt+C Alt+butterfly</kbd> and way easier to type than the fancy OS X symbols.

**Comment by oeed** [comment]
@demhydraz those are pretty unintuitive, even compared to the Mac system.

**Comment by viluon** [comment]
Oh you don't have a real butterfly @demhydraz? Really have to use the terrible emacs butterfly emulator? Poor you! 

In other words, pros of using (normal) long keyboard shortucts:
- Clear on first sight
- Used by Wikipedia ([link](https://en.wikipedia.org/wiki/Wikipedia:Keyboard_shortcuts), talking about how the shortcuts are displayed)
- Directly represent keys on the keyboard, do not use a dynamic mapping (which helps a great lot to keep user confusion to a minimum)
- Doesn't require users to read specifications and doesn't require collaborators to write the specifications to determine what key is meant by <kbd>M</kbd>, for example
- Guys let's just adopt this, it's [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

pros of using @demhydraz - suggested shortcuts
- They are faster to type

**Comment by lyqyd** [comment]
Full key names is absolutely the way to go on this one.

**Comment by oeed** [comment]
The issue I'm referring to is this. I'm obviously the first one to want to use the easiest system for the user, but I'm not sure key names is the greatest way.

As you can see, whenever you want to display a keyboard shortcut is consumes half the screen, and that's a pretty small shortcut. I might try to make a smaller font for it, but it's something to keep in mind; regular CC doesn't have that option. I do agree though, the OS X characters are confusing as hell.

![](http://puu.sh/mxzsn/4b7960d1d1.png)

![](http://puu.sh/mxzwF/7c79b8a473.png)

**Comment by viluon** [comment]
I don't really see the issue here @oeed, nobody says you should use full key shortcuts in your UI. We are talking about the keyboard shortcut notation in the _docs_ for the standard (or at least that's what I thought we were discussing).

**Comment by oeed** [comment]
@viluon I made this issue to discuss a UI keyboard shortcut standard. Hence, why I didn't include the meta tag ;)

**Comment by viluon** [comment]
@oeed Sorry for my misunderstanding then, but I think that the UI of a program is so specific there's no point in standardizing it... Also, I added the meta tag 3 days ago, you should have told me :stuck_out_tongue: 

Also,

> Agreed @oeed, but we are talking docs, not GUI here.

Why didn't you tell me? :stuck_out_tongue:

**Comment by oeed** [comment]
@viluon well the main thought behind this was seeing whether it was worth developing a universal way of expressing them for programs. Although given that 99% of the users won't read the spec there isn't really any point.
