### ISSUE TITLE
Support Code & Examples

### ISSUE THREAD

**Issue by demhydraz** [oeed/CraftOS-Standards#29]
Where should code for parsing/implementing a standard be thrown in? external pastebin link?

**Comment by viluon** [comment]
I mentioned GitHub and Pastebin in the README. It should definitely not stay here (the code). I'll solve it somehow in the `tutorial` branch.

**Comment by ardera** [comment]
I think there should be a link to it in a "See Also" section of the RFC, and the location of the implementation (pastebin, GitHub, etc) should not matter. The implementation should not really be necessary, since the RFC just describes the standard.

**Comment by demhydraz** [comment]
Well since this isn't the place I'mma go ahead and close this; @viluon if you feel it's nescessary to discuss this issue in more depth, feel free to reopen.
