### ISSUE TITLE
Better Organization

### ISSUE THREAD

**Issue by viluon** [oeed/CraftOS-Standards#3]
It would be a good idea to allow people to add labels (such as "File Format" or "Standard") to their PR's (does GitHub allow that for non-contributors?) or at least specify a format for PR titles to distinguish between repo organization-related PR's and actual standard definitions. Also, what about a README for every standard category (i.e. in every directory) saying e.g. what makes file format a file format? Just in case we'll get more complex standards later.

**Comment by oeed** [comment]
Like the labels idea! I'll make a bunch of them now, although yeah not sure if non-contributors can add titles.

I've also made a meta label to distinguish them from proposals.

I like that README in each category idea too.

**Comment by oeed** [comment]
Created a README for the file format category 99d5955.
