### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by viluon** [oeed/CraftOS-Standards#30]
How should different standards be licensed? In the 'real world', some might be proprietary. I suggest enforcing open source, submitters could however choose MIT or GPL. Worst case scenario should be (imo) that they are allowed to use [CC BY ND](http://creativecommons.org/licenses/by-nd/4.0/) or [CC BY NC ND](http://creativecommons.org/licenses/by-nc-nd/4.0/), but I am strongly against that to be honest.

**Comment by demhydraz** [comment]
What about the GNU FDL?

**Comment by oeed** [comment]
I'm of the opinion that we should not force a license upon people, it should be up to them.

**Comment by lxndio** [comment]
Possibly the [no license license](http://choosealicense.com/no-license/)?

**Comment by SquidDev** [comment]
I'd agree with @oeed on this one. Standards are about technologies/formats, rather than a way of developing things (though there are some standards on naming conventions and formatting).

**Comment by oeed** [comment]
I think we'll stick to not standardising licensing.

**Comment by viluon** [comment]
@oeed @SquidDev I wanted to prevent issues with copyright preventing the spread, use and (most importantly) future upgrades and fixes to proprietary standards.

**Comment by demhydraz** [comment]
I don't think we should enforce a specific license but we should force standards to be licensed under a free software license.

**Comment by lyqyd** [comment]
How do other standards bodies (e.g., IETF) handle this issue?  I'd suspect that copyright for the text of the standards themselves is held by the standards body, which then provides them under one consistent license.  Code examples are another issue.  I don't think a patchwork of licensing determined by the initial authors of various standards is a good idea, or even a practicable solution.  I think this issue should be re-opened for further discussion.

**Comment by oeed** [comment]
@viluon Standardising a license isn't going to stop someone from placing copyright on their code; if they want to do it they're just going to do it. I guess we could _recommend_ a license though.

@lyqyd I think we were mainly discussing licensing of code people write in their programs, but that is a good point. I'd say, regarding the license of the standards, the 'body' holds the copyright.

**Comment by viluon** [comment]
@oeed I wouldn't mind people to create proprietary utilities for dealing with the standards. I only want to ensure that something like [RAR](https://en.wikipedia.org/wiki/RAR_%28file_format%29) doesn't happen:

> ### Creating RAR Files
> 
> RAR files can be created _only_ with commercial software WinRAR, RAR, and other software that has written permission from Alexander Roshal or shares copyrighted code under license from Alexander Roshal. The software license agreements forbid reverse engineering.
> (...)

That is an example of great but dead technology. Great feature-wise, dead because of the way it is licensed. I wouldn't like to see any standards die.

**Comment by demhydraz** [comment]
I agree with @viluon. If we allow standards to RAR-ify then everything we've done goes to trash.

**Comment by oeed** [comment]
@viluon we have no authority to enforce a license though. One possibility would be to force _all_ programs posted on the forums to use a particular license, however.

**Comment by demhydraz** [comment]
> One possibility would be to force all programs posted on the forums to use a particular license, however.

[These](http://computercraft.info/forums2) forums? Or am I missing something?

Because we sure as hell have authority to enforce a license:

_Doesn't meet requirements, isn't merged._

**Comment by oeed** [comment]
Actually I misread what you said @viluon . I'd agree that all standards should be open source and should be publicly usable.

**Comment by viluon** [comment]
Agreed @oeed and @demhydraz, thanks! I therefore suggest ~~using~~ enforcing [free culture CC licenses](https://creativecommons.org/freeworks/) or [other mainstream open source ones](http://choosealicense.com/).

**Comment by oeed** [comment]
I'd vote GPL.

**Comment by demhydraz** [comment]
I'd vote GFDL.

**Comment by oeed** [comment]
Actually good point @demhydraz, GFDL is the more appropriate one.

**Comment by viluon** [comment]
The thing is, @oeed, that MIT for example is more permissive. If people want to give their work away completely (such as publishing it into the public domain), let them do it. [GFDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) seems to be a very good idea @demhydraz

**Comment by SquidDev** [comment]
I'd vote for something that allows people do do whatever they want with the standard without worrying about licensing, as long as they don't claim credit for it themselves. I feel GPL is too restrictive, and GFDL has similar problems.

**Comment by viluon** [comment]
MIT FTW @SquidDev, but then again, that might be _too free_. I'd just really go with any open source license available.

**Comment by demhydraz** [comment]
The GFDL has 'Documentation' (or is it Document?) in the name, guys.

**Comment by viluon** [comment]
I [linked](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) to it @demhydraz

**Comment by demhydraz** [comment]
No, you linked to the wikipedia page.

**Comment by demhydraz** [comment]
Also relevant:

> For example, the free online encyclopedia Wikipedia uses the GFDL (coupled with the Creative Commons Attribution Share-Alike License) for all of its text.

**Comment by oeed** [comment]
This is the main benefit right here:

> the original document or source code must be made available to the work's recipient

This means that people can build upon a standard within the terms of the license.

**Comment by viluon** [comment]
> No, you linked to the wikipedia page.

which literally says 

> GNU Free Documentation License

@demhydraz 

so GFDL everyone?

**Comment by demhydraz** [comment]
> All previous authors of the work must be attributed.

`git blame`

> All changes to the work must be logged.

`git log`

> Technical measures such as DRM may not be used to control or obstruct distribution or editing of the document.

Awesome!

GFDL is the perfect license for our needs. :+1:

**Comment by viluon** [comment]
### [GFDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) for the win!

**Comment by demhydraz** [comment]
*cough* I think you should let other people vote, too. @oeed @SquidDev

**Comment by viluon** [comment]
> This is the main benefit right here:
> 
> > the original document or source code must be made available to the work's recipient
> 
> This means that people can build upon a standard within the terms of the license.

~ @oeed

**Comment by oeed** [comment]
@viluon please incorporate this in to the tutorial, I'll add a license page now.

**Comment by oeed** [comment]
The decision has been made, but the appropriate files need to be updated, hence why this has been reopened.

**Comment by viluon** [comment]
Hmm, we might also want to create a `CONTRIBUTING.md` file @oeed. I have a feeling that GitHub treats it in a special way, and attaches a reminder to review it before submitting an issue or a PR.

**Comment by viluon** [comment]
[yep](https://github.com/blog/1184-contributing-guidelines), I was right

**Comment by oeed** [comment]
Any update on adding this to CONTRIBUTING.md @viluon?

**Comment by viluon** [comment]
Added to the `tutorial` branch in https://github.com/oeed/CraftOS-Standards/commit/d4f82fbe21ea5fe687a7216e1e77b9f874bf5b60, sorry for the delay @oeed.

**Comment by oeed** [comment]
Thanks @viluon!
