### ISSUE TITLE
Standard version numbers

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#31]
As stated by #2, all standards need to be given numbers.

File names should start with COS, followed by the standard number, a colon, then the name. For example, _S1: Paintutils Image_.

**Comment by superaxander** [comment]
So this naming is similar to rfc naming convention? Instead of RFC 1234 it'll be S1234?

**Comment by oeed** [comment]
Yeah, although I thought S was a bit too brief and ambiguous. I thought CCS might work (ComputerCraft Standard) although I'm completly open to any other suggestions. CCS isn't great with CraftOS 2 not really being ComputerCraft.

**Comment by superaxander** [comment]
COS(**C**raft**O**S **S**tandard) could be an option

**Comment by oeed** [comment]
Yeah okay, we'll go with COS, nice suggestion.

**Comment by oeed** [comment]
Updated in 8145363, closed.
