### ISSUE TITLE
Gitter Room

### ISSUE THREAD

**Issue by demhydraz** [oeed/CraftOS-Standards#5]
Having a place to discuss standards outside of github issues could be useful.

**Comment by oeed** [comment]
My main thoughts against doing this was the fact that when others join in the discussion half of it would be missing.

**Comment by lyqyd** [comment]
Between here and the CC forum, I think we're probably covered.  Is there significant benefit to be gained by adding a third place where discussions could happen?  I think that would end up being too fragmented.

**Comment by oeed** [comment]
On second thought, this would be rather useful as the oeed/Silica channel is getting a bit cluttered by messages related to this.

**Comment by viluon** [comment]
agreed @oeed!

**Comment by oeed** [comment]
https://gitter.im/oeed/CraftOS-Standards?utm_source=share-link&utm_medium=link&utm_campaign=share-link
