### ISSUE TITLE
File naming – should we include COS numbers?

### ISSUE THREAD

**Issue by oeed** [oeed/CraftOS-Standards#61]
Just wanting some thoughts on whether we should include COS numbers in the file name of standards. For example, `lua.md` would become something along the lines of `COS 2 - lua.md`.

Also, regarding file names that are acronyms (i.e. `tror.md`) should be also include the expanded name (i.e. `tror - terminal redirection over rednet.md`).

I can see the arguments for and against both, so interested to know what everyone else thinks.

**Comment by lyqyd** [comment]
I can see value including the COS number in the file name. I don't think it's necessary to spell out acronyms used in file names, though. That'll prevent them from getting too long. The difference for me is that finding out what an acronym means opening one file, whereas finding a COS number means opening every file.

Do we have a numeric index of COS number someplace?

**Comment by oeed** [comment]
> Do we have a numeric index of COS number someplace?

I believe not, that's something we should create and add to the merging process.

**Comment by viluon** [comment]
This has been addressed in #64, the general consensus seems to be **yes**. I believe this can be closed @oeed

**Comment by SquidDev** [comment]
I don't think this should be closed until we address this:

> I believe not, that's something we should create and add to the merging process.

It probably needs to be added to the getting started file (or contributing).

**Comment by viluon** [comment]
@SquidDev I don't think there's a need for a numeric COS index if #64 is merged.

**Comment by SquidDev** [comment]
I meant that people should be instructed to add their spec to the existing list as part of the PR process. Possibly also include the spec number in the PR title so we don't start using duplicate IDs.

**Comment by viluon** [comment]
@SquidDev I agree with adding to the list, but that is not a point of discussion for "should we include COS numbers in file names". Hence I suggest branching off to a new issue that would track the process of updating the meta docs, list updates included.

The spec number is only known *after* the standard is accepted though, so how would you know at the time of writing the PR title?
