### ISSUE TITLE
Standard Proposal Guidelines

### ISSUE THREAD

**Issue by viluon** [oeed/CraftOS-Standards#9]
@SquidDev's comment on #7 reminded me that there are no guidelines on how a Markdown proposal document should look like. Adding one should be fairly easy!

**Comment by demhydraz** [comment]
I suggest we adopt something close to IETF's memo guidelines.

**Comment by SquidDev** [comment]
What we probably want to avoid is sounding too legal like: whilst I understand the rational behind "MUST", "MUST NOT", "SHOULD NOT", etc... I don't think using those sorts of terms is a good idea on the friendly side of things.

**Comment by demhydraz** [comment]
Yea, I don't think we should adopt [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) (damn - is everything RFC'd?)
